apiVersion: v1
kind: Pod
metadata:
  name: dapi-go-limits-1core
  namespace: default
spec:
  containers:
    - name: test-container
      image: registry.k8s.io/busybox
      resources:
        limits:
          memory: 512Mi
          cpu: "1000m"
      command: [ "sh", "-c"]
      args:
      - while true; do
          echo -en '\n';
          printenv GOMEMLIMIT;
          printenv GOMAXPROCS;
          sleep 10;
        done;
      env:
        - name: GOMEMLIMIT
          valueFrom:
            resourceFieldRef:
              containerName: test-container
              resource: limits.memory
        - name: GOMAXPROCS
          valueFrom:
            resourceFieldRef:
              containerName: test-container
              resource: limits.cpu
  restartPolicy: Never